FROM nginx:alpine

# 复制构建产物到nginx html目录
COPY out/ /usr/share/nginx/html/

# 复制nginx配置
COPY nginx-docker.conf /etc/nginx/conf.d/default.conf

# 暴露80端口
EXPOSE 80

# 启动nginx
CMD ["nginx", "-g", "daemon off;"]

